version: '3.8'

services:
  db:
    image: mysql
    container_name: MONKEY_DB
    environment:
      MYSQL_ROOT_PASSWORD: monkey
      MYSQL_DATABASE: monkey_consulting
      MYSQL_USER: monkey
      MYSQL_PASSWORD: monkey
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
