spring:
  datasource:
    url: jdbc:mysql://monkey-consulting-bd.c7ae6qk6ehuy.us-east-1.rds.amazonaws.com/monkey_consulting
    username: root
    password: 847395M.

  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
