spring:
  application:
    name: monkey-consulting

  datasource:
    url: jdbc:mysql://localhost:3306/monkey_consulting
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: monkey
    password: monkey

  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

server:
  port: 8080
  servlet:
    context-path: /monkey-consulting

