spring:
  datasource:
    url: jdbc:mysql://127.0.0.7:3306/monkey_consulting
    username: monkey
    password: monkey

  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
